### ISSUE TITLE
/regen not working all the time

### ISSUE THREAD

**Issue by jusitnboggs** [Rotatceps/EE3Helper#1]
Once in a while when I use regen it doesn't add the EMC values for the items that added.

**Comment by Rotatceps** [comment]
I've looked further into it and it seems to only work if regen is performed an even number of times.
There's probably a step that I'm missing that gets covered on the second pass. An easy and dirty fix is to have it just run twice, but that's probably not desirable (especially when you've got a ton of mods).

## 

It can take some time for the values to show up after you run the regen command depending on how many mods you've got installed. EE3 should report to console once it's finished running dynamic EMC.

Additionally, you may have to either reload your world/reconnect/use EE3's sync command, as this mod currently doesn't trigger a server wide client sync when regen is run. This issue is explained here: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2442409-ee3-helper-2-2a-in-game-emc-value-management-emc?comment=21

I'll leave this issue open till I have time to add the feature I described in that post.

**Comment by Rotatceps** [comment]
Fixed

**Comment by Rotatceps** [comment]
Nevermind

**Comment by BraynStorm** [comment]
xD

**Comment by Rotatceps** [comment]
Starting to think this is an issue with the EE3 507 build. I'm going to try some things with a more recent one to see if the issue persists. Either way I have a few ideas for hacky workarounds.

**Comment by jusitnboggs** [comment]
Wait is there newer builds for EE3 i thought 507 was the lastest?

**Comment by Rotatceps** [comment]
Build is probably the wrong word. I'm pretty sure theres been a few updates to the repo since 507 so I'll be messing with whatever is up right now.

Also, wasn't 507 the recommended build at one point? Seems its seems like its an earlier one now. Or maybe im just trippin.

**Comment by jusitnboggs** [comment]
There page only shows up to 507
http://ee3.pahimar.com/
but maybe they just haven't compiled it yet.
