### ISSUE TITLE
Regen errors

### ISSUE THREAD

**Issue by jusitnboggs** [Rotatceps/EE3Helper#3]
16.09 02:59:43 [Server] INFO Exception in thread "DynamicEMC Thread" [02:59:43] [DynamicEMC Thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
16.09 02:59:43 [Server] DynamicEMC Thread/INFO [Equivalent Exchange 3]: Beginning dynamic value computation

That happen when i run regen and it doesn't do anything. that started doing it 2 days ago and can't get it working and my emc values are gone for almost everything as well as items not learning( they get learned for about 5 mins and then need relearned)

**Comment by Rotatceps** [comment]
Did you change anything between it working and not working?
What version of EE3 & EE3H are you using & other what mods/any specific pack/version of forge?

There's an issue that I think is being caused by EE3, but I haven't been able to confirm without a doubt yet.
Something along the lines of:
If you're in world and some items have automatically calculated values, and then you add a value to an item that's used in a recipe for another item and reconnect, the items that previously had values will lose their values. Reconnecting may or may not generate those values again, but the values of items that you should be able to be calculate because you've assigned a value to a particular item will no longer show. It'll also alternate between the two states every time you reconnect.

Regen basically simulates a world reload, so running regen produces this behavior as well (at least in my tests).

**Comment by jusitnboggs** [comment]
Here is my mod list.
http://pastebin.com/WyZ5FMqW

This is the pack
http://minecraft.curseforge.com/modpacks/234993-mcbuilds
EE3 Version 3.507
EE3H Version 2.2a

Also a side note when i was looking in the console today... I think this might be a ee3 bug and not a ee3H bug

When I start the server and EE3 goes to do its dyno EMC stuff it gives the same error wtih each pass it tries.

Edit: 1:20 PST
MY test server didn't error at all with the same mods/configs going to test with the same world now...
... ok so something in my servers "world" folder is casing it. I removed both ee3 folders from the world folder and it still errors...  Any ideas?

**Comment by jusitnboggs** [comment]
Any luck?

**Comment by Rotatceps** [comment]
Both mods have changed significantly, not sure if this is still an issue.
